### ISSUE TITLE
EN_Reboot: New storage UI

### ISSUE THREAD

**Issue by DabirSA** [Arks-Layer/PSO2ENPatchCSV#1663]
Translated/UI/ui_item.csv
- [x] WarehouseQuest_ReceivingWindow_Recipient_Message#0
- [x] WarehouseQuest_ReceivingWindow_AllReceive#0
- [x] WarehouseQuest_ReceivingWindow_AllBuy#0
- [x] WarehouseQuest_ReceivingWindow_ItemPackFull#0
- [x] WarehouseQuest_ReceivingWindow_ItemPackLittleSpace#0
- [x] WarehouseQuest_ReceivingWindow_WarehouseFull#0
- [x] WarehouseQuest_ReceivingWindow_WarehouseLittleSpace#0
- [x] WarehouseQuest_Receiving_Guidance_Window_title#0
- [x] WarehouseQuest_Receiving_Guidance_Window_mes#0
- [x] WarehouseQuest_Receiving_Confirm_MoveAll#0
